import { TONES } from "../../ui/tones";
import type { AuditAction, AuditEventRow, AuditSeverity } from "./types";

/** Action label + tone for badge rendering. */
export const ACTION_META: Record<AuditAction, { label: string; tone: string }> = {
  create: { label: "Created", tone: TONES.success.badge },
  update: { label: "Updated", tone: TONES.info.badge },
  delete: { label: "Deleted", tone: TONES.danger.badge },
  publish: { label: "Published", tone: TONES.accent.badge },
  unpublish: { label: "Unpublished", tone: TONES.neutral.badge },
  invite: { label: "Invited", tone: TONES.warn.badge },
  revoke: { label: "Revoked", tone: TONES.danger.badge },
  login: { label: "Signed in", tone: TONES.neutral.badge },
  logout: { label: "Signed out", tone: TONES.neutral.badge },
  export: { label: "Exported", tone: TONES.info.badge },
};

export const SEVERITY_META: Record<AuditSeverity, { label: string; tone: string }> = {
  info: { label: "Info", tone: TONES.neutral.badge },
  warn: { label: "Warn", tone: TONES.warn.badge },
  alert: { label: "Alert", tone: TONES.danger.badge },
};

/** Demo events — 14 rows. Reset on browser reload. */
export const SEED_EVENTS: AuditEventRow[] = [
  {
    id: "ev_14",
    at: "2026-05-20T08:42:00Z",
    actor: { id: "u_1", name: "Maya Kusumawardani", initials: "MK", role: "owner" },
    action: "publish",
    entityType: "page",
    entityId: "p_home",
    entityLabel: "Homepage hero",
    severity: "info",
    diffSummary: "status: draft → published",
    ipAddress: "103.21.244.18",
  },
  {
    id: "ev_13",
    at: "2026-05-20T08:14:00Z",
    actor: { id: "u_2", name: "Rahman Effendi", initials: "RE", role: "admin" },
    action: "update",
    entityType: "role",
    entityId: "r_editor",
    entityLabel: "Editor role",
    severity: "warn",
    diffSummary: "permissions: +manage:workflows",
    diff: {
      permissions: {
        before: ["create:pages", "edit:pages", "publish:pages"],
        after: ["create:pages", "edit:pages", "publish:pages", "manage:workflows"],
      },
    },
    ipAddress: "203.0.113.22",
  },
  {
    id: "ev_12",
    at: "2026-05-20T07:42:00Z",
    actor: { id: "u_2", name: "Rahman Effendi", initials: "RE", role: "admin" },
    action: "invite",
    entityType: "user",
    entityId: "u_4",
    entityLabel: "faisal@wirausaha.id",
    severity: "info",
  },
  {
    id: "ev_11",
    at: "2026-05-20T07:30:00Z",
    actor: { id: "u_3", name: "Diana Putri", initials: "DP", role: "editor" },
    action: "create",
    entityType: "post",
    entityId: "post_42",
    entityLabel: "Case study: Lumen rebrand",
    severity: "info",
  },
  {
    id: "ev_10",
    at: "2026-05-20T06:55:00Z",
    actor: { id: "u_3", name: "Diana Putri", initials: "DP", role: "editor" },
    action: "update",
    entityType: "page",
    entityId: "p_pricing",
    entityLabel: "Pricing — tiers section",
    severity: "info",
    diffSummary: "tiers[2].price: $99 → $129",
    diff: {
      "tiers[2].price": { before: 99, after: 129 },
      "tiers[2].label": { before: "Pro", after: "Pro (annual)" },
      updatedAt: { before: "2026-05-15T10:00:00Z", after: "2026-05-20T06:55:00Z" },
    },
  },
  {
    id: "ev_9",
    at: "2026-05-20T06:12:00Z",
    actor: { id: "u_sys", name: "System", initials: "SY", role: "system" },
    action: "export",
    entityType: "session",
    entityId: "sess_export_0520",
    entityLabel: "Daily session export",
    severity: "info",
  },
  {
    id: "ev_8",
    at: "2026-05-19T22:10:00Z",
    actor: { id: "u_3", name: "Diana Putri", initials: "DP", role: "editor" },
    action: "publish",
    entityType: "post",
    entityId: "post_41",
    entityLabel: "Newsletter: May digest",
    severity: "info",
  },
  {
    id: "ev_7",
    at: "2026-05-19T18:33:00Z",
    actor: { id: "u_1", name: "Maya Kusumawardani", initials: "MK", role: "owner" },
    action: "update",
    entityType: "setting",
    entityId: "s_brand",
    entityLabel: "Brand colors",
    severity: "info",
    diffSummary: "primary: #5b1d99 → #6d28d9",
    diff: {
      "colors.primary": { before: "#5b1d99", after: "#6d28d9" },
      "colors.primaryForeground": { before: "#ffffff", after: "#fafafa" },
    },
  },
  {
    id: "ev_6",
    at: "2026-05-19T14:01:00Z",
    actor: { id: "u_2", name: "Rahman Effendi", initials: "RE", role: "admin" },
    action: "delete",
    entityType: "webhook",
    entityId: "wh_old",
    entityLabel: "Legacy Zapier webhook",
    severity: "warn",
  },
  {
    id: "ev_5",
    at: "2026-05-19T11:46:00Z",
    actor: { id: "u_5", name: "Sari Nurhayati", initials: "SN", role: "viewer" },
    action: "login",
    entityType: "session",
    entityId: "sess_5_9912",
    entityLabel: "Browser session",
    severity: "info",
    ipAddress: "118.96.40.7",
  },
  {
    id: "ev_4",
    at: "2026-05-19T09:18:00Z",
    actor: { id: "u_2", name: "Rahman Effendi", initials: "RE", role: "admin" },
    action: "revoke",
    entityType: "user",
    entityId: "u_old",
    entityLabel: "former@konsultan.id",
    severity: "alert",
  },
  {
    id: "ev_3",
    at: "2026-05-18T20:55:00Z",
    actor: { id: "u_3", name: "Diana Putri", initials: "DP", role: "editor" },
    action: "create",
    entityType: "workflow",
    entityId: "wf_intake",
    entityLabel: "Lead intake automation",
    severity: "info",
  },
  {
    id: "ev_2",
    at: "2026-05-18T15:24:00Z",
    actor: { id: "u_1", name: "Maya Kusumawardani", initials: "MK", role: "owner" },
    action: "update",
    entityType: "role",
    entityId: "r_owner",
    entityLabel: "Owner role",
    severity: "warn",
    diffSummary: "transferred: u_old → u_1",
    diff: {
      ownerId: { before: "u_old", after: "u_1" },
      transferredAt: { before: null, after: "2026-05-18T15:24:00Z" },
    },
  },
  {
    id: "ev_1",
    at: "2026-05-18T08:00:00Z",
    actor: { id: "u_sys", name: "System", initials: "SY", role: "system" },
    action: "create",
    entityType: "setting",
    entityId: "s_init",
    entityLabel: "Workspace initialized",
    severity: "info",
  },
];
