/** Phosphor icon imports M-Z (split for ≤200 LOC file cap). */

import type { Icon } from "@phosphor-icons/react";
import {
  MagicWand,
  Magnet,
  MagnifyingGlass,
  MapPin,
  MapTrifold,
  Megaphone,
  Memory,
  Microphone,
  Microscope,
  Minus,
  Money,
  Monitor,
  Moon,
  Mountains,
  MusicNote,
  Network,
  Notebook,
  NotePencil,
  Package,
  PaintBrush,
  Palette,
  PaperPlaneTilt,
  Paperclip,
  Pause,
  Pencil,
  PencilLine,
  Percent,
  Phone,
  PhoneCall,
  Plant,
  Play,
  Plus,
  Pulse,
  PushPin,
  Question,
  Radio,
  Rainbow,
  Receipt,
  Rewind,
  Rows,
  Ruler,
  Scissors,
  ShareNetwork,
  ShoppingBag,
  ShoppingCart,
  Sigma,
  SkipBack,
  SkipForward,
  Sliders,
  Snowflake,
  Sparkle,
  SpeakerHigh,
  SpeakerSimpleHigh,
  Square,
  Stack,
  Star,
  Storefront,
  Sun,
  SunHorizon,
  Table,
  Tag,
  Target,
  Television,
  Timer,
  Tornado,
  Tray,
  Trash,
  Tree,
  TreeEvergreen,
  TrendDown,
  TrendUp,
  Triangle,
  Trophy,
  UploadSimple,
  User,
  UserCircle,
  UserMinus,
  UserPlus,
  Users,
  VideoCamera,
  Wallet,
  Wind,
  Wrench,
  X,
} from "@phosphor-icons/react";

export const PHOSPHOR_ICONS_B: Readonly<Record<string, Icon>> = {
  MagicWand, Magnet, MagnifyingGlass, MapPin, MapTrifold, Megaphone, Memory, Microphone,
  Microscope, Minus, Money, Monitor, Moon, Mountains, MusicNote, Network, Notebook,
  NotePencil, Package, PaintBrush, Palette, PaperPlaneTilt, Paperclip, Pause, Pencil,
  PencilLine, Percent, Phone, PhoneCall, Plant, Play, Plus, Pulse, PushPin, Question,
  Radio, Rainbow, Receipt, Rewind, Rows, Ruler, Scissors, ShareNetwork, ShoppingBag,
  ShoppingCart, Sigma, SkipBack, SkipForward, Sliders, Snowflake, Sparkle, SpeakerHigh,
  SpeakerSimpleHigh, Square, Stack, Star, Storefront, Sun, SunHorizon, Table, Tag,
  Target, Television, Timer, Tornado, Tray, Trash, Tree, TreeEvergreen, TrendDown,
  TrendUp, Triangle, Trophy, UploadSimple, User, UserCircle, UserMinus, UserPlus, Users,
  VideoCamera, Wallet, Wind, Wrench, X,
};
