/** Phosphor icon imports A-L (split for ≤200 LOC file cap). */

import type { Icon } from "@phosphor-icons/react";
import {
  Alarm,
  Archive,
  ArrowBendUpLeft,
  ArrowDown,
  ArrowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowSquareOut,
  ArrowUp,
  ArrowUpRight,
  Asterisk,
  At,
  Bell,
  Binary,
  Book,
  BookOpen,
  Bookmark,
  Books,
  BracketsCurly,
  BracketsRound,
  BracketsSquare,
  Briefcase,
  Bug,
  Buildings,
  Calculator,
  Calendar,
  CalendarBlank,
  CalendarCheck,
  Camera,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  ChartBar,
  ChartBarHorizontal,
  ChartLine,
  ChartPie,
  ChatCircle,
  ChatText,
  Check,
  CheckSquare,
  Circle,
  Clipboard,
  ClipboardText,
  Clock,
  Cloud,
  CloudArrowDown,
  CloudArrowUp,
  CloudLightning,
  CloudRain,
  CloudSnow,
  Code,
  Coins,
  Columns,
  Compass,
  Cpu,
  CreditCard,
  Crop,
  Crosshair,
  Crown,
  CurrencyDollar,
  Database,
  DeviceMobile,
  DeviceTablet,
  Diamond,
  Disc,
  Divide,
  DownloadSimple,
  Drop,
  Envelope,
  Equals,
  Eraser,
  Eye,
  EyeSlash,
  Eyedropper,
  FastForward,
  File,
  FileCode,
  FileText,
  FilmStrip,
  Flag,
  Flame,
  Flower,
  FlowArrow,
  Folder,
  FolderOpen,
  Funnel,
  Gear,
  GitBranch,
  GitCommit,
  GitMerge,
  GitPullRequest,
  GithubLogo,
  Globe,
  GridFour,
  Hammer,
  Handshake,
  HardDrives,
  Hash,
  Headphones,
  Heart,
  Hexagon,
  Highlighter,
  Hourglass,
  House,
  Image,
  Images,
  Info,
  Kanban,
  Key,
  Laptop,
  Lightning,
  Link,
  List,
  ListBullets,
  ListChecks,
  ListPlus,
  Lock,
  LockOpen,
} from "@phosphor-icons/react";

export const PHOSPHOR_ICONS_A: Readonly<Record<string, Icon>> = {
  Alarm, Archive, ArrowBendUpLeft, ArrowDown, ArrowDownRight, ArrowLeft, ArrowRight,
  ArrowSquareOut, ArrowUp, ArrowUpRight, Asterisk, At, Bell, Binary, Book, BookOpen,
  Bookmark, Books, BracketsCurly, BracketsRound, BracketsSquare, Briefcase, Bug,
  Buildings, Calculator, Calendar, CalendarBlank, CalendarCheck, Camera, CaretDown,
  CaretLeft, CaretRight, CaretUp, ChartBar, ChartBarHorizontal, ChartLine, ChartPie,
  ChatCircle, ChatText, Check, CheckSquare, Circle, Clipboard, ClipboardText, Clock,
  Cloud, CloudArrowDown, CloudArrowUp, CloudLightning, CloudRain, CloudSnow, Code,
  Coins, Columns, Compass, Cpu, CreditCard, Crop, Crosshair, Crown, CurrencyDollar,
  Database, DeviceMobile, DeviceTablet, Diamond, Disc, Divide, DownloadSimple, Drop,
  Envelope, Equals, Eraser, Eye, EyeSlash, Eyedropper, FastForward, File, FileCode,
  FileText, FilmStrip, Flag, Flame, Flower, FlowArrow, Folder, FolderOpen, Funnel,
  Gear, GitBranch, GitCommit, GitMerge, GitPullRequest, GithubLogo, Globe, GridFour,
  Hammer, Handshake, HardDrives, Hash, Headphones, Heart, Hexagon, Highlighter,
  Hourglass, House, Image, Images, Info, Kanban, Key, Laptop, Lightning, Link, List,
  ListBullets, ListChecks, ListPlus, Lock, LockOpen,
};

export { FileText as FallbackPhosphorIcon };
